#ifndef DEFINE_TOPF_H
#define DEFINE_TOPF_H

//#define DLG_TOPF                "[VBTOPF41]"

//--------------------------------Parameternahmen in der fmc-Datei
#define TOPF_TA        "ABSTTPF="
#define TOPF_A1        "ABST1="
#define TOPF_A2        "ABST2="
#define TOPF_A3        "ABST3="
#define TOPF_A4        "ABST4="
#define TOPF_A5        "ABST5="
#define TOPF_MA        "ABSTA="
#define TOPF_MB        "ABSTB="
#define TOPF_KETTE     "KETTE="
#define TOPF_GRUPPE    "GRP="
#define TOPF_SEITE     "BRICHT="
#define TOPF_MESSEI    "MRICHT="
#define TOPF_BODM      "DMDUEB="
#define TOPF_TODM      "DMTPF="
#define TOPF_BOTI      "TIDUEB="
#define TOPF_WKZ       "TNR="
#define TOPF_TOTI      "TITPF="
#define TOPF_ANBOTI    "LGEAN="
#define TOPF_BOANBOVO  "FANTPF="
#define TOPF_TOANBOVO  "FANDUEB="
#define TOPF_REBOMA    "LGEAB="
#define TOPF_BOBOVO    "FDUEB="
#define TOPF_TOBOVO    "FTPF="
#define TOPF_BOZSM     "ZSM="
#define TOPF_DREHZ     "N="
#define TOPF_PLM       "PLM="
#define TOPF_BEZ       "BEZB="
#define TOPF_AFB       "AFB="
#define TOPF_AUSGEBL   "@@@/=1"

//--------------------------------Parameternahmen der Variablen
//Variabelnnahmen müssen immer mit "[" beginnen und mit "]" enden
#define VAR_TOPF_TA        "[TA]"
#define VAR_TOPF_A1        "[A1]"
#define VAR_TOPF_A2        "[A2]"
#define VAR_TOPF_A3        "[A3]"
#define VAR_TOPF_A4        "[A4]"
#define VAR_TOPF_A5        "[A5]"
#define VAR_TOPF_MA        "[MA]"
#define VAR_TOPF_MB        "[MB]"
#define VAR_TOPF_KETTE     "[KM]"
#define VAR_TOPF_GRUPPE    "[GRP]"
#define VAR_TOPF_SEITE     "[BS]"
#define VAR_TOPF_MESSEI    "[MEB]"
#define VAR_TOPF_BODM      "[DD]"
#define VAR_TOPF_TODM      "[TD]"
#define VAR_TOPF_BOTI      "[DT]"
#define VAR_TOPF_WKZ       "[TNR]"
#define VAR_TOPF_TOTI      "[TT]"
#define VAR_TOPF_ANBOTI    "[ABT]"
#define VAR_TOPF_BOANBOVO  "[AVD]"
#define VAR_TOPF_TOANBOVO  "[ABV]"
#define VAR_TOPF_REBOMA    "[RBM]"
#define VAR_TOPF_BOBOVO    "[BVD]"
#define VAR_TOPF_TOBOVO    "[BZ]"
#define VAR_TOPF_BOZSM     "[ZSM]"
#define VAR_TOPF_DREHZ     "[N]"
#define VAR_TOPF_PLM       "[PLM]"
#define VAR_TOPF_AFB       "[AFB]"

#endif // DEFINE_TOPF_H
